### ISSUE TITLE
In the second tutorial for Game.java, you forgot to release one of the callbacks.

### ISSUE THREAD

**Issue by MrsDogood** [sriharshachilakapati/LWJGL-Tutorial-Series#1]
In [this version of Game.java](https://github.com/sriharshachilakapati/LWJGL-Tutorial-Series/blob/1ec0189920c64afa5fe877b5d85a1a4d71a208ad/src/com/shc/tutorials/lwjgl/Game.java) you forgot to release keyCallback.

**Comment by sriharshachilakapati** [comment]
I'm sorry for the late reply, but that is already fixed in a next commit. This is not an issue anymore. I will be careful not to make these kinds of mistakes anymore.
